### ISSUE TITLE
Cannot Load Cartridge

### ISSUE THREAD

**Issue by bugraakcan** [Accenture/adop-cartridge-skeleton#5]
I'm running DevOps Academy Labs Module 3/Optional Task: Cartridges part.
[https://alm.accenture.com/wiki/display/DOT/Optional+Task%3A+Cartridges]

Getting the following error when trying to load the cartridge in step 6. There also other persons getting the same error as seen in comments.

++ export TOKEN_WORKSPACE_FOLDER_NAME=DOA
++ TOKEN_WORKSPACE_FOLDER_NAME=DOA
+++ echo DOA/Labs/Development
+++ cut -d/ -f2
++ export TOKEN_PROJECT_FOLDER_NAME=Labs
++ TOKEN_PROJECT_FOLDER_NAME=Labs
++ export TOKEN_GIT_CREDENTIAL=adop-jenkins-master
++ TOKEN_GIT_CREDENTIAL=adop-jenkins-master
++ export 'TOKEN_GERRIT_SERVER=ADOP Gerrit'
++ TOKEN_GERRIT_SERVER='ADOP Gerrit'
+++ ls 'xml/*.template'
ls: cannot access xml/*.template: No such file or directory
Script returned: []
Processing DSL script skeleton_pipeline_jobs.groovy
ERROR: startup failed:
workspace:/cartridge/jenkins/jobs/dsl/skeleton_pipeline_jobs.groovy: 4: unable to resolve class SCMProvider 
 @ line 4, column 13.
   SCMProvider scmProvider = SCMProviderHandler.getScmProvider("${SCM_PROVIDER_ID}", binding.variables)

**Comment by RobertNorthard** [comment]
@bugraakcan I am closing this issue as the cartridge loads without issue.

**Comment by kymcaris** [comment]
Hello, I'm having the same problem.
